# Generated by Django 5.2.4 on 2025-07-28 04:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('boda', 'Boda'), ('cumpleaños', 'Cumpleaños'), ('baby_shower', 'Baby Shower'), ('graduacion', 'Graduación'), ('otro', 'Otro')], max_length=50)),
                ('fecha_evento', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('guardado_como_borrador', models.BooleanField(default=True)),
                ('ultimo_guardado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('enlace_unico', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG')], max_length=50)),
                ('destinatario_nombre', models.CharField(max_length=100)),
                ('destinatario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('destinatario_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('metodo_envio', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('max_acompanantes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='invitations.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invitado', models.CharField(max_length=100)),
                ('acompanantes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('menu_opcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('invitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion', to='invitations.invitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('config_diseno', models.JSONField()),
                ('es_publica', models.BooleanField(default=True)),
                ('es_temporal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitations.plantilla'),
        ),
    ]
