# Generated by Django 5.2.4 on 2025-08-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='config_diseno',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
