# Generated by Django 5.2.4 on 2025-07-24 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ultimo_guardado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='max_acompanantes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='es_temporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
